### PR TITLE
Interface up?

### PR DESCRIPTION
**Pull request by Vanders**
Implement up? for Interfaces so that you can check the link state (which in turn tells you if the interface is configured correctly and the Right Things happened):
```
describe interface('eth0') do
  it { should be_up }
end
```

### CODE REVIEW

**Comment by mizzy** [comment]
Other types uses `be_enabled`, so I think it is consistent to use `be_enabled`. How do you think about it ?

**Comment by Vanders** [comment]
I see what you mean. Giving it some thought, I think "enabled" is tricky when it's applied to a network interface; most people would naturally call an interface "up" or "down", so that strikes me as the most natural mapping when writing Serverspec tests. There's also a slight problem that "enabled" may be an overloaded term; certainly on Cumulus Linux, but even on plain Linux, "enabled" may be confused for "exists". "exists" and "up" seem less ambiguous?

If you have very strong feelings on this then I'd be happy to make the change though, but I think "be_up" might be better for things like network interfaces.

**Comment by mizzy** [comment]
I understand that you said. You're right. So you don't need to fix it. I will merge this patch as is.
Thanks a lot!

**Comment by mizzy** [comment]
Released as v2.16.0.

**Pull request merged**
