### PR TITLE
Add new checks for password change days

### PR DESCRIPTION
**Pull request by ryandoyle**
Add checks for `have_minimum_password_change_days` and `have_maximum_password_change_days`.

This has a dependency on an unreleased version of specinfra as per serverspec/specinfra#378.

So the specs currently fail until a newly released serverspec (and should have its gemspec updated accordingly).

### CODE REVIEW

**Comment by ryandoyle** [comment]
As expected, the PR failed until serverspec/specinfra#378 is merged

**Comment by mizzy** [comment]
I'm thinking we should use the matchers which RSpec has by default as much as possible.

So this sytax is prefer:

```ruby
describe user('foo') do
  its(:maximum_password_change_days) == 99999
end
```

With this syntax, we can use other operators like this:
```ruby
describe user('foo') do
  its(:maximum_password_change_days) < 99999
end
```

And I feel that `maximum_password_change_days` is ambiguous a bit.
How about `maximum_password_valid_days` ?

**Comment by ryandoyle** [comment]
Hi @mizzy I will update serverspec to use the `its` syntax. 

The question I have is: Is it really worth adding the extra abstraction with `specinfra`? Am I better off just running the command?

EG:
```
def minimum_password_change_days
  @runner.run_command("chage -l #{@name} ...")
end 
```

Or should I still do it via specinfra?
```
def minimum_password_change_days
  @runner.minimum_user_password_change_days(@name)
end 
```

Looking at a recent example, `x509_certificate`, it uses the `@runner.run_command` directly. And from what I can tell its not generic either - it requires that the system is a *nix based system.

It seems there is some inconsistency in regards to what uses specinfra abstractions and what doesn't.

**Comment by ryandoyle** [comment]
I've updated both serverspec and specinfra for now. I've changed the syntax to:

```
describe user('ryan') do
  its(:minimum_days_between_password_change) { should == 0 } 
  its(:maximum_days_between_password_change) { should == 99999 }                                                                                                                                  
end
```

**Comment by mizzy** [comment]
> I will update serverspec to use the its syntax.

Thanks!

> The question I have is: Is it really worth adding the extra abstraction with specinfra? Am I better off just running the command?

It is OK to write the OS independent command like `openssl` directory. If the command and options do not vary from OSes(Linux, BSD, Solaris, AIX ...), abstraction is not needed. (I'm ignoring Windows, because I don't use it. If Windows users would like to use that kind of function, they should fix the function to work on Windows by themselves.)

So if `chage` command works on every OSes supported by Serverspec/Specinfra in a similar way, it is OK to write it directory.
 
Or you can write directory even though it does not work on every OSes. When the abstraction will be needed, someone who need the abstraction will fix it.  (Threre is a phrase "Premature optimization is the root of all evil.")  You don't need to care the OSes which you don't use.

**Comment by mizzy** [comment]
Thanks for fixing. Is `minimum_days_between_password_changes` more correct English ? I'm not native English speaker, so I don't thell which is good `password_change` and `password_changes`.

**Comment by ryandoyle** [comment]
Hi @mizzy, as a native english speaker, `minimum_days_between_password_change` sounds more correct. 

Also, I am basically using the same language that is used when running `chage`. See below as an exmaple

```
~ $ chage -l ryan
Last password change					: Dec 04, 2013
Password expires					: never
Password inactive					: never
Account expires						: never
Minimum number of days between password change		: 0
Maximum number of days between password change		: 99999
Number of days of warning before password expires	: 7
```

**Comment by mizzy** [comment]
I see. Thanks!

**Comment by mizzy** [comment]
Released as v2.15.0.

**Comment by ryandoyle** [comment]
Thanks, I'll issue a pull request tonight to add the documentation to the website as well

**Comment by mizzy** [comment]
> I'll issue a pull request tonight to add the documentation to the website as well

I appreciate it very much. Thanks!

**Pull request merged**
