### PR TITLE
add types x509_certificate, x509_private_key, specs for both

### PR DESCRIPTION
**Pull request by aschmidt75**
ssl/tls configuration is a source of bugs, so it would be nice to be able to write serverspecs for that as well.

## X.509 Certificates

Be able to
* check if a file is an openssl certificate
* check it its valid, now < notAfter lifetime
* check its DNs, subjects, issuer, email, alias, ...
* check its purposes (i.e. being a client certificate)
* check length of key (i.e >= 2048) 
* check the remaining days of validity

```ruby
describe x509_certificate('/etc/ssl/certs/some_cert.pem') do
        it { should be_certificate }

        it { should be_valid }
        its(:validity_in_days) { should_not be < 100 }
        its(:validity_in_days) { should be >= 100 }

        its(:subject) { should eq '/C=DE/O=What/OU=Ever/CN=Root CA' }
        its(:issuer) { should match  /O=What/ }
        its(:issuer) { should_not match  /O=FoobarComp/ }
        its(:email) { should be_empty }
   
        it { should have_purpose 'SSL server CA' }
        it { should_not have_purpose 'SSL server' }

        its(:keylength) { should be >= 2048 }
end
```

## RSA Keys

Be able to
* ensure that an rsa key is encrypted (or not)
* ensure key integrity (is_valid)
* check if the private key matches to a public certificate

```ruby
describe x509_private_key('/my/private/server-key.pem') do
        it { should_not be_encrypted }
        it { should be_valid }
        it { should have_matching_certificate('/my/certs/server-cert.pem') }
end
```

As of now, `openssl` will be used as the library frontend for dealing with RSA keys and X.509 private keys.

### CODE REVIEW

**Comment by mizzy** [comment]
OpenSSL is just one of the SSL libraries. So I don't like the name `openssl_certificate` and `openssl_key`. `x509_certificate` and `x509_private_key` would be better.

**Comment by aschmidt75** [comment]
good point, changed names to x509.

**Comment by mizzy** [comment]
Thanks!

**Comment by mizzy** [comment]
Released as v2.10.0.

**Comment by aschmidt75** [comment]
Great, thanks! May i provide documentation for https://github.com/serverspec/serverspec.github.io as PR or would you prefer to maintain docs yourself?

**Comment by mizzy** [comment]
> May i provide documentation for https://github.com/serverspec/serverspec.github.io as PR 

Yes, please.

**Pull request merged**
